// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_x4vpy1LHn6p4VBQs3gvw8-VxZqwbu-o',
    appId: '1:136471538487:web:84b2bc05956711027588b2',
    messagingSenderId: '136471538487',
    projectId: 'project-20d66',
    authDomain: 'project-20d66.firebaseapp.com',
    storageBucket: 'project-20d66.firebasestorage.app',
    measurementId: 'G-53F57FCE41',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMxMx_WwaSB25prwBx_MhKJkZYcdqwqeE',
    appId: '1:136471538487:android:2affe69595532af07588b2',
    messagingSenderId: '136471538487',
    projectId: 'project-20d66',
    storageBucket: 'project-20d66.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPZADclFYKsjLc_FUBRIRxK3GaJlGv74M',
    appId: '1:136471538487:ios:a7a19b65be7b54537588b2',
    messagingSenderId: '136471538487',
    projectId: 'project-20d66',
    storageBucket: 'project-20d66.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );
}
